#!/bin/bash
#SBATCH --job-name=test_other_pr
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=0-00:15:00
#SBATCH --mem=20gb
#SBATCH --output=Array.%A_%a.log
#SBATCH --array=0-15 #Set this to number of runs or index's of name_list
#SBATCH -p q64,q36,q24
##SBATCH --begin=now+1hour
##SBATCH -p q32g
##SBATCH --gres gpu
source /home/${USER}/.bashrc
conda activate tf_gpu

# #srun python3 -u extractFeatures.py
# #srun python3 -u mainSnapEval.py
# #srun python3 -u mainPlanes.py
# #srun python3 -u mainSnapEval_stats.py

#srun python3 -u update_data.py
#srun python3 -u "/home/au643300/DataHandling/notebooks/22-10-21_make_slices.py"
#srun python3 -u /home/au643300/DataHandling/notebooks/10-11-21_heat_1vary.py
echo This is task $SLURM_ARRAY_TASK_ID
#srun python3 -u /home/au643300/DataHandling/notebooks/26-11-21_better_load_val.py
#srun python3 -u /home/au643300/DataHandling/notebooks/08-12-21_test_at_other_pr.py
srun python3 -u /home/au643300/DataHandling/notebooks/26-11-21_plots_new_approch.py