#!/bin/bash
#SBATCH --job-name=Snapstat
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=0-12:30:00
#SBATCH --mem=30gb
#SBATCH --output=Array.%A_%a.log
#SBATCH --array=0-13 #Set this to number of runs
#SBATCH -p q64,q36,q24
##SBATCH --begin=now+2hour
source /home/${USER}/.bashrc
conda activate tf_gpu

# #srun python3 -u extractFeatures.py
# #srun python3 -u mainSnapEval.py
# #srun python3 -u mainPlanes.py
# #srun python3 -u mainSnapEval_stats.py

#srun python3 -u update_data.py
#srun python3 -u "/home/au643300/DataHandling/notebooks/22-10-21_make_slices.py"
#srun python3 -u /home/au643300/DataHandling/notebooks/10-11-21_heat_1vary.py
echo This is task $SLURM_ARRAY_TASK_ID
#srun python3 -u /home/au643300/DataHandling/notebooks/26-11-21_better_load_val.py
srun python3 -u /home/au643300/DataHandling/notebooks/26-11-21_plots_new_approch.py

