#!/bin/bash
#SBATCH --job-name=snapStat
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mincpus=4
#SBATCH --time=2-0:00:00
#SBATCH --mem=20gb
#SBATCH -p q64,q36,q24,

#  srun python3 -u extractFeatures.py
# #srun python3 -u mainSnapEval.py
# #srun python3 -u mainPlanes.py
# #srun python3 -u mainSnapEval_stats.py
srun python3 -u for_run.py
# ¤srun python3 -u update_records.py