#!/bin/bash
#SBATCH --job-name=snapStat
#SBATCH --ntasks=1
#SBATCH --cpus-per-task 4
#SBATCH --mincpus=4
#SBATCH --time=2-0:00:00
#SBATCH --mem=25gb
#SBATCH -p q32g
#SBATCH --gres gpu

q32g="srun  -p q32g --job-name "Ml_test" --cpus-per-task 8 --mem=50gb  --time 10:00:00 --gres gpu --pty bash"


#  srun python3 -u extractFeatures.py
# #srun python3 -u mainSnapEval.py
# #srun python3 -u mainPlanes.py
# #srun python3 -u mainSnapEval_stats.py
#srun python3 -u for_run.py
srun python3 -u /home/au643300/DataHandling/notebooks/30_09_21_CNN_proper_transpose.py