#!/bin/bash
#SBATCH --job-name=snapStat
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mincpus=8
#SBATCH --time=1-00:00:00
#SBATCH --mem=50gb
#SBATCH -p q64,q36

#  srun python3 -u extractFeatures.py
# #srun python3 -u mainSnapEval.py
# #srun python3 -u mainPlanes.py
srun python3 -u Save_serial.py